<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TGGAttributeConstraint" nsURI="platform:/resource/org.emoflon.ibex.tgg.runtime.democles/model/TGGAttributeConstraint.ecore"
    nsPrefix="TGGAttributeConstraint">
  <eClassifiers xsi:type="ecore:EClass" name="AttributeConstraint" eSuperTypes="platform:/plugin/org.gervarro.democles.specification.emf/model/specification.ecore#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
